"""Add foiling and art_style fields to Card model

Revision ID: 0fdc9548ed30
Revises: 
Create Date: 2025-08-28 20:58:36.567842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdc9548ed30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foiling', sa.String(length=20), nullable=False, server_default='NF'))
        batch_op.add_column(sa.Column('art_style', sa.String(length=20), nullable=False, server_default='normal'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('art_style')
        batch_op.drop_column('foiling')

    # ### end Alembic commands ###
