"""Add pickup_location field to Order model

Revision ID: 962304bea846
Revises: e43a4dde2df4
Create Date: 2025-08-29 02:23:26.969215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962304bea846'
down_revision = 'e43a4dde2df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_location', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('pickup_location')

    # ### end Alembic commands ###
