"""Remove sale-related fields from inventory items

Revision ID: e2098e5db12e
Revises: add_listed_for_sale_column
Create Date: 2025-09-01 21:47:27.213647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2098e5db12e'
down_revision = 'add_listed_for_sale_column'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        # Remove sale-related fields
        batch_op.drop_column('sale_price')
        batch_op.drop_column('is_for_sale')
        batch_op.drop_column('show_in_shop')
        batch_op.drop_column('listed_for_sale')

        # Update existing columns
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('foil_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('is_mint',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        # Restore sale-related fields
        batch_op.add_column(sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_for_sale', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('show_in_shop', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('listed_for_sale', sa.Boolean(), nullable=False, default=False))

        # Restore original column types
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('foil_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('is_mint',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    # ### end Alembic commands ###
