"""Add user management fields and audit logging

Revision ID: user_mgmt_001
Revises: f1234567890
Create Date: 2025-09-01 19:58:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'user_mgmt_001'
down_revision = 'e2098e5db12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # User fields already exist in database, only create audit tables

    # Create user_audit_logs table
    op.create_table('user_audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['users.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create verification_audit_logs table
    op.create_table('verification_audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('inventory_item_id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=20), nullable=False),
        sa.Column('previous_status', sa.Boolean(), nullable=True),
        sa.Column('new_status', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['users.id']),
        sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes for performance
    op.create_index('idx_users_account_status', 'users', ['account_status'])
    op.create_index('idx_users_role', 'users', ['role'])
    op.create_index('idx_users_created_at', 'users', ['created_at'])
    op.create_index('idx_users_last_login', 'users', ['last_login'])
    op.create_index('idx_user_audit_logs_user_id', 'user_audit_logs', ['user_id'])
    op.create_index('idx_user_audit_logs_admin_id', 'user_audit_logs', ['admin_id'])
    op.create_index('idx_user_audit_logs_action', 'user_audit_logs', ['action'])
    op.create_index('idx_user_audit_logs_created_at', 'user_audit_logs', ['created_at'])
    op.create_index('idx_verification_audit_logs_inventory_item_id', 'verification_audit_logs', ['inventory_item_id'])
    op.create_index('idx_verification_audit_logs_admin_id', 'verification_audit_logs', ['admin_id'])
    op.create_index('idx_verification_audit_logs_action', 'verification_audit_logs', ['action'])
    op.create_index('idx_verification_audit_logs_created_at', 'verification_audit_logs', ['created_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index('idx_verification_audit_logs_created_at')
    op.drop_index('idx_verification_audit_logs_action')
    op.drop_index('idx_verification_audit_logs_admin_id')
    op.drop_index('idx_verification_audit_logs_inventory_item_id')
    op.drop_index('idx_user_audit_logs_created_at')
    op.drop_index('idx_user_audit_logs_action')
    op.drop_index('idx_user_audit_logs_admin_id')
    op.drop_index('idx_user_audit_logs_user_id')
    op.drop_index('idx_users_last_login')
    op.drop_index('idx_users_created_at')
    op.drop_index('idx_users_role')
    op.drop_index('idx_users_account_status')

    # Drop tables
    op.drop_table('verification_audit_logs')
    op.drop_table('user_audit_logs')

    # Drop columns from users table
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'suspension_expires')
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'last_login')

    # ### end Alembic commands ###